name: gh-pages
on:
  push:
    branches: '*'
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Cron
        run: |
          npm install
          npm run cron
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: gh-pages
          build_dir: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
